# Generated by Django 2.2 on 2019-05-18 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='q_id',
        ),
    ]
